### ISSUE TITLE
Step 3 didn't work for me

### ISSUE THREAD

**Issue by lucadonnoh** [somenano/Tutorials#1]
I solved using `"{\"password\": \"xxx\"}"` instead of `'{"password": "xxx"}'`

**Comment by pawapps** [comment]
What shell are you using to run `curl`?

**Comment by lucadonnoh** [comment]
cmd

**Comment by pawapps** [comment]
Yeah i guess that makes sense.  I'll update to the escaped double quote to make the tutorial as cross-platform as possible.  Appreciate the report!
